
"***********************************************" ;
/* The next step update functions for all cases */

w10(n) := r*p + v(n+1) ;
w01(n) := r*Ap(n) + v(1) ;
w11(n) := r*(p+Ap(n) - 2*p*Ap(n)) + p*Ap(n)*v_11 + (1 - p*Ap(n))*v_pp ; 

w10_p1 : r*p + v(1) ;
w01_p1 : r   + v(1) ;
w11_p1 : r*(1+p-2*p) + p*v_11 + (1-p)*v_pp ;

w10_11 : r + v_p1 ;
w01_11 : r + v_p1 ;
w11_11 : v_11 ;

w10_pp : r*p + v(1) ;
w01_pp : r*p + v(1) ;
w11_pp : r*(2*p - 2*p^2) + p^2*v_11 + (1-p^2)*v_pp ;

/*
  vim: ft=maxima
*/
